# Brain Shell Autostarts
exec-once = awww-daemon
exec-once = hypridle
exec-once = quickshell -c $HOME/.local/src/Brain_Shell
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
source = $HOME/.config/Brain_Shell/Brain_ShellKeybinds.conf
